language: java

sudo: required

script: "mvn cobertura:cobertura"

services:
  - docker

jdk:
  - openjdk7

cache:
    directories:
        - $HOME/.m2
        - docker
        - ~/.m2/repository

branches:
  only:
  - deploy

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - export CH_VERSION=$(docker run -v $(pwd):/chime bitbrain/chime:latest CHANGELOG.md version)
  - export CH_TEXT=$(docker run -v $(pwd):/chime bitbrain/chime:latest CHANGELOG.md text)
  - mvn versions:set -DnewVersion=$CH_VERSION
  - chmod +x deployment/before-deploy.sh
  - chmod +x deployment/deploy.sh
  - chmod +x deployment/deploy-javadoc.sh
  - ./deployment/before-deploy.sh

install:
  - ./deployment/deploy.sh

after_success:
  - ./deployment/deploy-javadoc.sh
  - bash <(curl -s https://codecov.io/bash)
