codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 3
  round: down
  range: "65...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "demo/**/*"
  - "deployment/**/*"
  - "core/src/main/java/de/bitbrain/braingdx/ai/**/*"
  - "core/src/main/java/de/bitbrain/braingdx/postprocessing/**/*"
  - "core/src/main/java/de/bitbrain/braingdx/tweens/**/*"
  - "core/src/main/java/de/bitbrain/braingdx/screens/**/*"
